### ISSUE TITLE
Add Jest tests

### ISSUE THREAD

**Issue by davidzwa** [mkevenaar/CharlieSpring#15]
This adds the jest tests with mongodb-memory-server

## Expected Behavior

.

## Current Behavior

Code is tested by running, this makes it hard to test underlying atomic operations like database queries.

## Possible Solution

Add jest with a in-memory database

## Steps to Reproduce (for bugs)

1.

## Context

Testing

**Comment by mkevenaar** [comment]
:tada: This issue has been resolved in version 0.1.0 :tada:
