### ISSUE TITLE
Discord's "default" emojis can't be reaction roles if they are not also unicode emojis

### ISSUE THREAD

**Issue by Stones8000** [mkevenaar/CharlieSpring#19]
## Expected Behavior
If I were to put a discord emoji into the "emoji" field of the "/reactions roles add" command, it should work.

## Current Behavior
For some reason, it only works if the "default discord emoji" is also an emoji in unicode. For example, the :flag_eu: emoji is a discord-made emoji that isn't in unicode and the bot cannot understand it.
![image](https://user-images.githubusercontent.com/79322708/168105705-f8714b24-9d31-4014-b937-25c67da9eb70.png)
![image](https://user-images.githubusercontent.com/79322708/168105811-629f430b-bb23-4ca0-9113-58dfe7eab940.png)

## Steps to Reproduce (for bugs)
1. Using the "/reactions roles add" command, use an emoji that is not in unicode but is default on discord
2. Wait for the bot's response :)

## Context

I was making a regions reaction category for regional roles, here is an example of the previous one we used with carl-bot:
![image](https://user-images.githubusercontent.com/79322708/168109295-f1e5278b-50d0-4436-aa4b-59ed8544b854.png)

**Comment by mkevenaar** [comment]
@Stones8000 This has been solved and should be available in less then 1h

**Comment by mkevenaar** [comment]
:tada: This issue has been resolved in version 0.1.0 :tada:
