### ISSUE TITLE
Reaction roles

### ISSUE THREAD

**Issue by mkevenaar** [mkevenaar/CharlieSpring#6]
Bot should have reaction roles,

Configuration options:
* channel
* category, new category triggers a new message
* Reaction role:
  * role (e.g. @13-15)
  * description (e.g. 13-15 year old)
  * emoji
  * category (e.g. age)

**Comment by Lucxjo** [comment]
If you'd like I can take a look at this on the weekend. I think that it's going to be the easiest of the features to implement. How do you think the category wants implementing? Just list it in the embed description?

**Comment by mkevenaar** [comment]
I am thinking about something like this:

**Age roles** [name of the category]
Select the your age from the roles below [description of the category]
* 👶 13-15 years @\13-15 [Emoji - description - role (only shown if description is empty; backslash added to not tag someone) ]
* 👦 16-18 years @\16-18
* 👨 18+ @\18+

This is just an example tho

**Comment by mkevenaar** [comment]
Oh, the bot should create the message in a configurable channel. Also the message should be updated with new roles if added, leaving the current emojis obviously. Should respond with that emoji to assist the users selecting the correct role

role should be deletable too.

Needles to say, once an emoji is triggered, the role should be added / removed to the user, depending on the action

**Comment by mkevenaar** [comment]
:tada: This issue has been resolved in version 0.1.0 :tada:
